name: docker

on: push

jobs:
  docker:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: checkout
      # - uses: actions/setup-node@v2
      #   name: nodejs-setup
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Push Docker image
        with:
          image: tomoya0517/react
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: run
        run: | 
          docker run -d --rm --name react tomoya0517/react
          echo "hello"
          ls 
